Angular init + authorization
ozhurova/Budget-app pull request #5
Opened 2022-03-23 13:52 UTC by ozhurova

1. Angular init
2. Added Angular Material
3. Created main page, error page
4. Added api service, auth service, user service
5. Added auth guard
![1 1](https://user-images.githubusercontent.com/82470486/159713097-ba816abc-ab61-45b6-abfb-4f1416ab3f9b.png)
![1 2](https://user-images.githubusercontent.com/82470486/159713209-2ae97f19-a2a9-4c98-9a53-7bbe6e18f4a8.png)
![1 3](https://user-images.githubusercontent.com/82470486/159713227-58352ba6-a836-4222-b2b0-bd8cf5189cbc.png)
![1 4](https://user-images.githubusercontent.com/82470486/159713245-60d177d3-0339-415c-a119-1b4101a55679.png)
![1 5](https://user-images.githubusercontent.com/82470486/159714486-bc3ca337-cfb7-4791-a835-7709338dddeb.png)

2022-03-28 15:07 UTC, Morphine-medicine requested changes
Looks really great! Take a look on comments, and after fixing it, let me know, even if it will be done after deadline, I'll approve that HW 5 is done, great job!

2022-03-28 15:07 UTC, Morphine-medicine commented on client/src/app/core/components/login-modal/login-modal.component.html
> +  <form *ngIf="isLogin" class="login-wrapper" [formGroup]="loginForm">
looks good, but I'll recommend you to change structure to 
```
<ng-container *ngIf="isLogin; else registerTemplate">
<form class="login-wrapper" [formGroup]="loginForm">
....
</form>
</ng-container>

<ng-template #registerTemplate>
<form class="login-wrapper" [formGroup]="registerForm">
...
</form>
</ng-template>
```
OR you can create form, looking on isLogin, and you will have 1 template for both fuctions, and for Name formControl you can use ngIf

2022-03-28 15:07 UTC, Morphine-medicine commented on client/src/app/core/components/login-modal/login-modal.component.html
> +      <button mat-raised-button color="primary" class="mat-btn-primary" (click)="cancel()">
no need to use ngIf because it's inside the same ngIf

2022-03-28 15:09 UTC, Morphine-medicine commented
And also, I'll recommend toi add some paddings for header, mb 16px it will look better)

2022-03-28 19:49 UTC, ozhurova commented on client/src/app/core/components/login-modal/login-modal.component.html
> +  <form *ngIf="isLogin" class="login-wrapper" [formGroup]="loginForm">
if I make one generic template and one form, but how do I determine which user I received in order to make the correct api request?

2022-03-29 09:28 UTC, ozhurova commented on client/src/app/core/components/login-modal/login-modal.component.html
> +  <form *ngIf="isLogin" class="login-wrapper" [formGroup]="loginForm">
I changed to <ng-container> and <ng-template>

2022-03-29 09:31 UTC, ozhurova commented on client/src/app/core/components/login-modal/login-modal.component.html
> +      <button mat-raised-button color="primary" class="mat-btn-primary" (click)="cancel()">
I fixed it on a new branch, but now I've fixed it here

2022-03-29 09:31 UTC, ozhurova commented on client/src/app/core/components/header/header.component.html
> +<app-login-modal *ngIf="isVisible" (modal)="closeModal()" [isLogin]="isLogin" [title] = title></app-login-modal>
fixed it

2022-04-04 10:50 UTC, merged